/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ArmflexArchState.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ArmflexArchState.pb-c.h"
void   armflex_arch_state_p__init
                     (ArmflexArchStateP         *message)
{
  static const ArmflexArchStateP init_value = ARMFLEX_ARCH_STATE_P__INIT;
  *message = init_value;
}
size_t armflex_arch_state_p__get_packed_size
                     (const ArmflexArchStateP *message)
{
  assert(message->base.descriptor == &armflex_arch_state_p__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t armflex_arch_state_p__pack
                     (const ArmflexArchStateP *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &armflex_arch_state_p__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t armflex_arch_state_p__pack_to_buffer
                     (const ArmflexArchStateP *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &armflex_arch_state_p__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ArmflexArchStateP *
       armflex_arch_state_p__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ArmflexArchStateP *)
     protobuf_c_message_unpack (&armflex_arch_state_p__descriptor,
                                allocator, len, data);
}
void   armflex_arch_state_p__free_unpacked
                     (ArmflexArchStateP *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &armflex_arch_state_p__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor armflex_arch_state_p__field_descriptors[4] =
{
  {
    "xregs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ArmflexArchStateP, n_xregs),
    offsetof(ArmflexArchStateP, xregs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ArmflexArchStateP, pc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ArmflexArchStateP, sp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nzcv",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ArmflexArchStateP, nzcv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned armflex_arch_state_p__field_indices_by_name[] = {
  3,   /* field[3] = nzcv */
  1,   /* field[1] = pc */
  2,   /* field[2] = sp */
  0,   /* field[0] = xregs */
};
static const ProtobufCIntRange armflex_arch_state_p__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor armflex_arch_state_p__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ArmflexArchState_p",
  "ArmflexArchStateP",
  "ArmflexArchStateP",
  "",
  sizeof(ArmflexArchStateP),
  4,
  armflex_arch_state_p__field_descriptors,
  armflex_arch_state_p__field_indices_by_name,
  1,  armflex_arch_state_p__number_ranges,
  (ProtobufCMessageInit) armflex_arch_state_p__init,
  NULL,NULL,NULL    /* reserved[123] */
};
