util-obj-$(CONFIG_ARMFLEX) += armflex.pb-c.o
util-obj-$(CONFIG_ARMFLEX) += armflex-communication.o
util-obj-$(CONFIG_ARMFLEX) += armflex-page-demander.o
util-obj-$(CONFIG_ARMFLEX) += armflex-verification.o
util-obj-$(CONFIG_ARMFLEX) += armflex.o
